let STARTING_CHIPS = 500;
let STARTING_DEALER_POSITION = 0;
let TURN_TIMEOUT = "NONE";
let POST_DEAL_SLEEP_TIME = 2000;
let MAX_PLAYERS = 9;



module.exports = {
  STARTING_CHIPS,
  STARTING_DEALER_POSITION,
  TURN_TIMEOUT,
  POST_DEAL_SLEEP_TIME,
  MAX_PLAYERS,
}
